<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Component\Console\Application' shared autowired service.

$this->services['Symfony\\Component\\Console\\Application'] = $instance = new \Symfony\Component\Console\Application();

$instance->add(new \App\Command\CreateUserCommand());

return $instance;
