<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPaOtKh\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPaOtKh/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerGPaOtKh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerGPaOtKh\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerGPaOtKh\srcApp_KernelDevContainer([
    'container.build_hash' => 'GPaOtKh',
    'container.build_id' => 'b17a04dd',
    'container.build_time' => 1571842638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPaOtKh');
